---
title: "CP_WY_2022-23 AWS"
author: "Wyatt Reis"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(dplyr)
library(lubridate)
library(plotly)
library(ggplot2)
library(cowplot)
library(ggprism)
```

```{r importing data, echo=FALSE}
# Import data with simple header
# Unburned AWS - hourly
uf_hourly <- read.table('C:/Users/wyatt/OneDrive - Colostate/MS Research/Cameron Peak Fire/WY 2022-23/Data/AWS/UF_Wx/CR1000_7_One_Hour_1105.dat', sep = ",", header = TRUE, skip = "1") %>%
  slice(., -(1:2)) %>%
  mutate(TIMESTAMP = as.POSIXct(TIMESTAMP, tz = "UTC"), 
         TIMESTAMP = as.POSIXct(format(TIMESTAMP, tz = "us/mountain", orgin = 'UTC', usetz = TRUE))) %>%
  mutate_if(is.character,as.numeric) %>%
  mutate(site = 'uf_wx') 

# Unburned North AWS - hourly
ufn_hourly <- read.table('C:/Users/wyatt/OneDrive - Colostate/MS Research/Cameron Peak Fire/WY 2022-23/Data/AWS/UFN_Wx/CR1000_Elder_1_One_Hour_1105.dat', sep = ",", header = TRUE, skip = "1") %>%
  slice(., -(1:2)) %>%
  mutate(TIMESTAMP = as.POSIXct(TIMESTAMP, tz = "UTC"), 
         TIMESTAMP = as.POSIXct(format(TIMESTAMP, tz = "us/mountain", orgin = 'UTC', usetz = TRUE))) %>%
  mutate_if(is.character,as.numeric) %>%
  mutate(site = 'ufn_wx') 

# Burned AWS - hourly
bf_hourly <- read.table('C:/Users/wyatt/OneDrive - Colostate/MS Research/Cameron Peak Fire/WY 2022-23/Data/AWS/BF_Wx/CR1000XSeries - new_Hourly_1105.dat', sep = ",", header = TRUE, skip = "1") %>%
  slice(., -(1:2)) %>%
  mutate(TIMESTAMP = as.POSIXct(TIMESTAMP, tz = "UTC"), 
         TIMESTAMP = as.POSIXct(format(TIMESTAMP, tz = "us/mountain", orgin = 'UTC', usetz = TRUE))) %>%
  mutate_if(is.character,as.numeric) %>%
  mutate(site = 'bf_wx') 

# Burned North AWS - hourly
bfn_hourly <- read.table('C:/Users/wyatt/OneDrive - Colostate/MS Research/Cameron Peak Fire/WY 2022-23/Data/AWS/BFN_Wx/CR1000_Elder_3_One_Hour_1105.dat', sep = ",", header = TRUE, skip = "1") %>%
  slice(., -(1:2)) %>%
  mutate(TIMESTAMP = as.POSIXct(TIMESTAMP, tz = "UTC"), 
         TIMESTAMP = as.POSIXct(format(TIMESTAMP, tz = "us/mountain", orgin = 'UTC', usetz = TRUE))) %>%
  mutate_if(is.character,as.numeric) %>%
  mutate(site = 'bfn_wx') 

# Burned South AWS - hourly
bfs_hourly <- read.table('C:/Users/wyatt/OneDrive - Colostate/MS Research/Cameron Peak Fire/WY 2022-23/Data/AWS/BFS_Wx/CR1000_Elder_2_One_Hour_1105.dat', sep = ",", header = TRUE, skip = "1") %>%
  slice(., -(1:2)) %>%
  mutate(TIMESTAMP = as.POSIXct(TIMESTAMP, tz = "UTC"), 
         TIMESTAMP = as.POSIXct(format(TIMESTAMP, tz = "us/mountain", orgin = 'UTC', usetz = TRUE))) %>%
  mutate_if(is.character,as.numeric) %>%
  mutate(site = 'bfs_wx') 

# Combine all imported hourly data into one df
all_hr <- bind_rows(bf_hourly, bfn_hourly, bfs_hourly, uf_hourly, ufn_hourly) %>%
  filter(TIMESTAMP >= as.POSIXct("2022-10-01 00:00:00", tz = 'us/mountain')) %>%
  relocate(site, .after = TIMESTAMP)
```

```{r}
# data checks 
# battery
BattV <- ggplot(all_hr) +
  geom_line(aes(x = TIMESTAMP, y = BattV_Min, color = site))#+
  facet_wrap(~site, ncol = 1)

ggplotly(BattV)

#air temp
AirTemp <- ggplot(all_hr) +
  geom_line(aes(x = TIMESTAMP, y = AirTC_Avg, color = site))#+
  facet_wrap(~site, ncol = 1)

ggplotly(AirTemp)

#RH
RH <- ggplot(all_hr) +
  geom_line(aes(x = TIMESTAMP, y = RH, color = site))#+
  facet_wrap(~site, ncol = 1)

ggplotly(RH)

#Snow Depth
SnowDepth <- ggplot(all_hr) +
  geom_line(aes(x = TIMESTAMP, y = DBTCDT_Avg, color = site))#+
  facet_wrap(~site, ncol = 1)

ggplotly(SnowDepth)

#wind speed
WindSpd <- ggplot(all_hr) +
  geom_line(aes(x = TIMESTAMP, y = WS_ms_Avg, color = site))#+
  facet_wrap(~site, ncol = 1)

ggplotly(WindSpd)

#wind speed
WindDir <- ggplot(all_hr) +
  geom_line(aes(x = TIMESTAMP, y = WindDir, color = site))+
   scale_y_continuous(expand = c(0,0), limits = c(0,360), breaks = seq(0,360,90), 
                      guide = guide_prism_minor()) #+
  facet_wrap(~site, ncol = 1)

ggplotly(WindDir)
```
